---
title: "Untitled"
author: "Daniel"
date: "23 september 2019"
output:
  html_document:
    df_print: paged
---

## R Markdown

```{r}
MSEP <- function(factors, dt) {
  sqsum <- 0
  N <- dim(dt)[1]
  
  for (i in 1:N) {
    
    excluded_obs <- dt[i,]
    excluded_mpg <- (excluded_obs[7] + excluded_obs[8])/2
    if (is.na(excluded_obs[1])== FALSE) {
      new_dt <- dt
      new_dt[i,] <- NA
      
      
      manufacturer <- new_dt$manufacturer
      car_model <- new_dt$model
      type <- new_dt$type
      minprice <- new_dt$minprice
      midprice <- new_dt$midprice
      maxprice <- new_dt$maxprice
      cmpg <- new_dt$cmpg
      hmpg <- new_dt$hmpg
      airbags <- new_dt$airbags # discrete
      drivetrain <- new_dt$drivetrain # discrete
      cylinders <- new_dt$cylinders # missing values
      enginesize <- new_dt$enginesize
      horsepower <- new_dt$horsepower
      rpm <- new_dt$rpm
      enginerev <- new_dt$enginerev
      manualtransmissions <- new_dt$manualtransmissions # discrete
      fueltankcap <- new_dt$fueltankcap
      passcap <- new_dt$passcap
      lencar <- new_dt$lencar
      wheelbase <- new_dt$wheelbase 
      width <- new_dt$width
      Uturn <- new_dt$Uturn
      rearseatroom <- new_dt$rearseatroom
      luggagecap <- new_dt$luggagecap # missing values
      weight <- new_dt$weight
      domestic <- new_dt$domestic # discrete
      
      mpg <- (cmpg + hmpg)/2
      
      modelform <- as.formula(paste("mpg~", paste(factors, collapse="+")))
    
      model <- lm(modelform, data=new_dt, na.action = na.omit)
  
      coef <- coefficients(model)
      
      est_val <- coef[1]
      
      for (j in 1:length(factors)) {
        est_val <- est_val + coef[j + 1]*excluded_obs[which(colnames(dt)==factors[j])]
      }
      
      sqsum <- sqsum + (excluded_mpg-est_val)^2
      
    }
    
  }
  
  MSEP <- sqsum/N 
  print(paste("mpg~", paste(factors, collapse="+")))
  print(MSEP[1,])

}
```

```{r, echo=FALSE}

cars <- read.table("A17-cars-win.dat", header = FALSE, col.names=c("manufacturer","model","type","minprice","midprice","maxprice", "cmpg", "hmpg", "airbags", "drivetrain", "cylinders", "engingesize", "horsepower", "rpm", "enginerev", "manualtransmissions", "fueltankcap", "passcap", "lencar", "wheelbase", "width", "uturn", "rearseatroom", "luggagecap", "weight", "domestic"))
cars <- as.data.frame(cars)
cars

minprice <- cars$V4
midprice <- cars$V5
maxprice <- cars$V6
cmpg <- cars$V7
hmpg <- cars$V8
airbags <- cars$V9 # discrete
drivetrain <- cars$V10 # discrete
cylinders <- cars$V11 # missing values
enginesize <- cars$V12
horsepower <- cars$V13
rpm <- cars$V14
enginerev <- cars$V15
manualtransmissions <- cars$V16 # discrete
fueltankcap <- cars$V17
passcap <- cars$V18
lencar <- cars$V19
wheelbase <- cars$V20 
width <- cars$V21
Uturn <- cars$V22
rearseatroom <- cars$V23
luggagecap <- cars$V24 # missing values
weight <- cars$V25
domestic <- cars$V26 # discrete
mpg <- c()



average <- 0

for (i in 1:length(cmpg)) {
  average <- (cmpg[i] + hmpg[i])/2
  mpg <- c(mpg, average)
}

```


```{r}
MSEP(c("width"), cars)
MSEP(c("weight","wheelbase","fueltankcap","passcap","enginerev","minprice","domestic"), cars)
MSEP(c( "wheelbase", "fueltankcap", "passcap",
    "enginerev","minprice", "domestic"), cars)

```


```{r, echo=FALSE}
pairs(~mpg + weight + wheelbase + fueltankcap + passcap + 
     + enginesize + minprice + rpm)

```


```{r, echo=FALSE}
model1 <- step(lm(mpg~1), scope=(~minprice + midprice + maxprice + enginesize + horsepower + rpm + enginerev + fueltankcap + passcap + lencar + wheelbase + width + Uturn + rearseatroom + weight + domestic), direction="both")


```

```{r, echo=FALSE}

summary(model1)
plot(model1)
```

```{r, echo=FALSE}
plot(fitted(model1), mpg)
abline(1,1)
```
```{r, echo=FALSE}
modeldom <- lm(formula = mpg ~ weight + wheelbase + fueltankcap + passcap + 
    enginerev + enginesize + minprice + rpm + domestic)

summary(modeldom)
plot(modeldom)
plot(fitted(modeldom), mpg)
abline(1,1)
```


```{r, echo=FALSE}
fitted(model)



```
```{r}
mpg



```

```{r}
model3 <- lm(mpg ~ weight + wheelbase + fueltankcap + passcap + 
    enginerev + enginesize + minprice)
summary(model3)

```

```{r}
model4 <- lm(mpg ~ weight + wheelbase + fueltankcap + passcap + 
    enginerev + enginesize + minprice + domestic)
summary(model4)
plot(model4)

```

```{r}
vif(model4)
```


```{r}
model5 <- lm(mpg ~ weight + wheelbase + passcap + 
    enginerev + enginesize + minprice + domestic)
summary(model5)
plot(model5)
```

```{r}
vif(model5)
```


```{r}
model6 <- lm(mpg ~ wheelbase + fueltankcap + passcap + 
    enginerev + enginesize + minprice + domestic)
summary(model6)
plot(model6)
```
```{r}
RMSEP <- function() {
  N <- length(mpg)
  MSum <- 0
  
  for (i in 1:N){
    
    ev <- cars[1,]
    
    tempcars <- cars[-c(i),]
    
    tempmpg <- (tempcars$V7 + tempcars$V8)/2
    tempweight <- tempcars$V25
    tempwheelbase <- tempcars$V20
    temppasscap <- tempcars$V18
    tempenginerev <- tempcars$V15
    tempenginesize <- tempcars$V12
    tempminprice <- tempcars$V4
    tempdomestic <- tempcars$V26
    
    tempmodel <- lm(tempmpg ~ tempweight + tempwheelbase + temppasscap + 
    tempenginerev + tempenginesize + tempminprice + tempdomestic)
    
    mc <- coefficients(tempmodel)
    
    fittedvalue_at_ex <- mc[1] + mc[2]*ev[25] + mc[3]*ev[20] + mc[4]*ev[18] + mc[5]*ev[15] + mc[6]*ev[12] + mc[7]*ev[4] + mc[8]*ev[26]    
    MSum <- MSum + ((ev[7] + ev[8])/2 - fittedvalue_at_ex)^2
  }
  msep <- MSum/N
  print(msep)
  print(sqrt(msep))
}

RMSEP()

 
```

```{r}
modeleq <- mpg ~ wheelbase + fueltankcap + passcap + enginerev + 
    enginesize + minprice + domestic

model <- lm(formula = modeleq)
summary(model)
```


```{r}
anova(model4, model5)
```


```{r}


newMSEP <- function(variable_indexes) {
  
  sum <- 0
  
  for (i in 1:93){ 
    excluded_row <- cars[i,]
    tcars <- cars[-c(i),]
    tmpg <- c((tcars[7] + tcars[8])/2)
    
    model <- lm(tmpg ~ tcars[,variable_indexes])
    
    coeff <- coefficients(model)
  
    fittedy <- 0
    
    for (k in 1:coeff) {
      if (k == 1){
        fittedy <- fittedy + coeff[k]
      }
      else {
        fittedy <- fittedy + coeff[k]*excluded_row[variable_indexes[k]]
      }
    }
    
    sum <- sum + (tmpg-fittedy)^2
  }
  
  msep <- sum/93
  
  print(msep)
  
}

newMSEP(c(4, 19))
```

```{r}
cars[, c(1,26)]
```
```{r}
model7 <- lm(mpg ~ reformulate(cars[,c(4,26)]), data=cars)
```



```{r}
index <- 80
cars[80,1]

```

